### PR TITLE
Convert all amber ions

### PR DESCRIPTION
**Pull request by mattwthompson**
This is #239 but not from a fork

```shell
$ git remote add aizvorski git@github.com:aizvorski/openmmforcefields.git
$ git fetch --all
$ git checkout aizvorski/convert-all-amber-ions
$ git checkout -b convert-all-amber-ions
$ git push upstream convert-all-amber-ions
```

Feel free to push to this branch if the original feature branch is updated.

### CODE REVIEW

**Comment by mattwthompson** [comment]
I have `pytest openmmforcefields/tests/test_amber_import.py::test_ffxml_import -nauto` passing locally - we'll see if the runners agree

**Comment by mattwthompson** [comment]
Okay, CI is passing now; there were some non-trivial changes brought in by merging upstream, so it might be worth another look. I'm not sure if the `amber/` folder should be blown away or not, the two XML files could be duplicates or unused.

I also can't comment on the meat of the original PR #239 - my objective here is to get that work closer to the finish line; feel free to push directly to this branch if more work is needed.

**Comment by mikemhenry** [comment]
Would be good to have @aizvorski take a look at this

**Review by jchodera — APPROVED** [review]
This looks good to me!

Thanks so much for putting in the hard work to contribute this, @aizvorski and @mattwthompson!

**Comment by aizvorski** [comment]
@mattwthompson Thank you very much for doing this!  That was a tough merge

A couple of renames and this should be good to go:

amber/opc.xml -> openmmforcefields/ffxml/amber/opc.xml
amber/opc3.xml -> openmmforcefields/ffxml/amber/opc3.xml

Could you possibly do that?  I'd do it but I'm not sure how :)

**Comment by mattwthompson** [comment]
Let's see if that works

**Comment by mattwthompson** [comment]
Okay, I think that worked. @aizvorski good to merge, do you think? Or @jchodera can merge when he gets to this next. I just don't want to do it without a final check.

**Comment by aizvorski** [comment]
@mattwthompson Yep, good to merge!  Thanks again

**Pull request merged**
