### PR TITLE
Update imports and tests for OpenMM 7.6

### LINKED ISSUE #172: Tests failing on OpenMM 7.6
Just noticed that our tests are now failing now that OpenMM 7.6 has been released:
https://github.com/openmm/openmmforcefields/runs/3448054973?check_suite_focus=true#step:7:121

### PR DESCRIPTION
**Pull request by jchodera**
This PR attempts to update all imports and test file paths for OpenMM 7.6, pinning to >=7.6.

Fixes #172

### CODE REVIEW

**Comment by jchodera** [comment]
@peastman: Tests will not pass and `openmmtools` will be broken until we fix the ParmEd issue: https://github.com/ParmEd/ParmEd/issues/1185
```

args = (<Topology; 1 chains, 150 residues, 2423 atoms, 2443 bonds>,)
kwargs = {'xyz': [Vec3(x=24.996000000000002, y=49.389, z=27.32), Vec3(x=24.563000000000002, y=50.251000000000005, z=27.02), Vec...00000004, z=26.500000000000004), Vec3(x=23.893, y=48.375, z=27.6), Vec3(x=23.533000000000005, y=48.05, z=26.623), ...]}

    @wraps(fcn)
    def new_fcn(*args, **kwargs):
        if not HAS_OPENMM:
            raise ImportError('Could not find or import OpenMM')
        if not SUPPORTED_VERSION:
>           raise ImportError('You must have at least OpenMM 6.3 installed')
E           ImportError: You must have at least OpenMM 6.3 installed

/usr/share/miniconda/envs/test/lib/python3.9/site-packages/parmed/utils/decorators.py:30: ImportError
```

**Comment by jchodera** [comment]
This is blocked until https://github.com/conda-forge/parmed-feedstock/pull/15 is merged and the ParmEd conda-forge packages are released.

**Comment by jchodera** [comment]
@peastman : Are new packages not deployed yet? I'm just getting
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (<Topology; 1 chains, 150 residues, 2423 atoms, 2443 bonds>,)
kwargs = {'xyz': [Vec3(x=24.996000000000002, y=49.389, z=27.32), Vec3(x=24.563000000000002, y=50.251000000000005, z=27.02), Vec...00000004, z=26.500000000000004), Vec3(x=23.893, y=48.375, z=27.6), Vec3(x=23.533000000000005, y=48.05, z=26.623), ...]}

    @wraps(fcn)
    def new_fcn(*args, **kwargs):
        if not HAS_OPENMM:
            raise ImportError('Could not find or import OpenMM')
        if not SUPPORTED_VERSION:
>           raise ImportError('You must have at least OpenMM 6.3 installed')
E           ImportError: You must have at least OpenMM 6.3 installed
```

**Comment by jchodera** [comment]
@peastman : I'll let you sort out the OpenMM 7.6 issues from here. I have no idea what to do.

**Comment by peastman** [comment]
I think it's happening because you aren't installing ParmEd directly.  Instead you install ambertools and get ParmEd from it.

https://github.com/openmm/openmmforcefields/blob/65fb59eb27c54d2243088eedb6380d9451050f3d/devtools/conda-envs/test_env.yaml#L23

The constraint on OpenMM version was only added to the `parmed` package, not the `ambertools` package.  Fixes could include directly listing ParmEd as a dependency or setting an upper bound on OpenMM in test_env.yaml.

**Comment by jchodera** [comment]
> The constraint on OpenMM version was only added to the parmed package, not the ambertools package. Fixes could include directly listing ParmEd as a dependency or setting an upper bound on OpenMM in test_env.yaml.

@peastman : I don't understand. `ambertools` depends on `parmed`:
image

Why wouldn't the constraint solver identify the correct combination of constraints that include the latest OpenMM (7.6.0) and the latest ParmEd compatible with it (3.4.3)? If this isn't happening, we haven't actually fixed the issue. There should be absolutely no need to specify parmed explicitly or an explicit parmed version unless things are still broken for everyone.

**Comment by jchodera** [comment]
It is indeed [correctly installing parmed 3.4.3 now](https://github.com/openmm/openmmforcefields/pull/173/checks?check_run_id=3514875980#step:6:143). We're just running into the bug introduced from merging #156

**Comment by jchodera** [comment]
@peastman : Now that GLYCAM support has been merged and ParmEd has been updated, hopefully we can get this cleaned up, merged, and released to provide openmmforcefields support for OpenMM 7.6!

**Pull request merged**
