### PR TITLE
Remove OpenEye from CI

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
Interesting, looks like we are getting this error https://github.com/openmm/openmmforcefields/actions/runs/4738608018/jobs/8412646819#step:9:1152 even not on this PR but on our main CI

**Comment by mikemhenry** [comment]
`FAILED openmmforcefields/tests/test_template_generators.py::TestSMIRNOFFTemplateGenerator::test_energies - RuntimeError: C=O could not be fully assigned charges. Charges were assigned to atoms set() but the molecule contains {0, 1, 2, 3}.`

**Comment by mattwthompson** [comment]
That error bubbles up from Interchange, either a wrapped toolkit(s) is unavailable or some combination of them can't assign charges to formaldehyde

**Comment by mattwthompson** [comment]
I don't have time to go deep on this but I can at least provide drive-by reassurance that our infrastructure isn't choking on that molecule when used directly:

```python
>>> from openff.toolkit import ForceField, Molecule
>>> ForceField("openff-2.0.0.offxml").create_interchange(Molecule.from_smiles("C=O").to_topology())
Interchange with 7 collections, non-periodic topology with 4 atoms.
```

An older version (0.2.3) of Interchange is installed in this case but I doubt the error is directly in the Interchange source anyway.

If you end up digging into this and get stuck at some point, I can answer any questions though

**Comment by ijpulidos** [comment]
I think the real problem comes from testing that molecule with the `'smirnoff99Frosst-1.0.6.offxml'` force field. The real problem is as usual trying to catch a generic exception in https://github.com/openmm/openmmforcefields/blob/main/openmmforcefields/generators/template_generators.py#L1283

When we try to read that force field file with the `openff-toolkit` we get the following (please expand the details):

<details>

```python
In [1]: openff.toolkit.typing.engines.smirnoff.ForceField("smirnoff99Frosst-1.0.6.offxml")
0.1 SMIRNOFF spec file does not contain 'potential' attribute for 'Bonds' tag. The SMIRNOFF spec converter is assuming it has a value of 'harmonic'
0.1 SMIRNOFF spec file does not contain 'potential' attribute for 'Angles' tag. The SMIRNOFF spec converter is assuming it has a value of 'harmonic'
0.1 SMIRNOFF spec file does not contain 'potential' attribute for 'ProperTorsions' tag. The SMIRNOFF spec converter is assuming it has a value of 'charmm'
0.1 SMIRNOFF spec file does not contain 'potential' attribute for 'vdW' tag. The SMIRNOFF spec converter is assuming it has a value of 'Lennard-Jones-12-6'
0.1 SMIRNOFF spec did not allow the 'Electrostatics' tag. Adding it in 0.2 spec conversion, and assuming the following values:
	method: PME
	scale12: 0.0
	scale13: 0.0
	scale15: 1.0
	cutoff: 9.0
	cutoff_unit: angstrom
0.1 SMIRNOFF spec file does not contain 'method' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of 'cutoff'
0.1 SMIRNOFF spec file does not contain 'combining_rules' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of 'Lorentz-Berthelot'
0.1 SMIRNOFF spec file does not contain 'scale12' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of '0.0'
0.1 SMIRNOFF spec file does not contain 'scale13' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of '0.0'
0.1 SMIRNOFF spec file does not contain 'scale15' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of '1'
0.1 SMIRNOFF spec file does not contain 'switch_width' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of '1.0'
0.1 SMIRNOFF spec file does not contain 'switch_width_unit' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of 'angstrom'
0.1 SMIRNOFF spec file does not contain 'cutoff' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of '9.0'
0.1 SMIRNOFF spec file does not contain 'cutoff_unit' attribute for 'NonBondedMethod/vdW'' tag. The SMIRNOFF spec converter is assuming it has a value of 'angstrom'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-21c9004e424b>", line 1, in <module>
    openff.toolkit.typing.engines.smirnoff.ForceField("smirnoff99Frosst-1.0.6.offxml")
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 307, in __init__
    self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 768, in parse_sources
    self._load_smirnoff_data(
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 876, in _load_smirnoff_data
    smirnoff_data = convert_all_strings_to_quantity(smirnoff_data)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 233, in convert_all_strings_to_quantity
    smirnoff_data[key] = convert_all_strings_to_quantity(value)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 233, in convert_all_strings_to_quantity
    smirnoff_data[key] = convert_all_strings_to_quantity(value)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 233, in convert_all_strings_to_quantity
    smirnoff_data[key] = convert_all_strings_to_quantity(value)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 238, in convert_all_strings_to_quantity
    smirnoff_data[index] = convert_all_strings_to_quantity(item)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 233, in convert_all_strings_to_quantity
    smirnoff_data[key] = convert_all_strings_to_quantity(value)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 246, in convert_all_strings_to_quantity
    obj_to_return = object_to_quantity(smirnoff_data)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 318, in _
    return string_to_quantity(obj)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/openff/toolkit/utils/utils.py", line 200, in string_to_quantity
    quantity = unit.Quantity(quantity_string)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/pint/facets/plain/quantity.py", line 209, in __new__
    inst = ureg.parse_expression(value)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 1255, in parse_expression
    return build_eval_tree(gen).evaluate(
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/pint/pint_eval.py", line 114, in evaluate
    left = self.left.evaluate(define_op, bin_op, un_op)
  File "/home/user/miniconda3/envs/openmmforcefields-dev/lib/python3.10/site-packages/pint/pint_eval.py", line 120, in evaluate
    raise DefinitionSyntaxError('missing unary operator "%s"' % op_text)
pint.errors.DefinitionSyntaxError: missing unary operator "*"
```

</details>

So, as far as I can see the smirk string `"[*:1]~[*:2]"` (in the force field file) is getting confused as a pint `Quantity` and generating that `DefinitionSyntaxError` when processing it. @mattwthompson you might know better about how this behaves in the `openff-toolkit` world, so any thoughts are appreciated.

**Comment by mattwthompson** [comment]
I've seen this error before - could you link the log it comes from?

**Comment by ijpulidos** [comment]
@mattwthompson I was just trying to reproduce the test failing in my local workstation and that's what I stumbled upon. The whole log for my local pytest run is in https://gist.github.com/ijpulidos/5699d11f8c8b7bac9706ae6b1c5da469 if that helps

**Comment by ijpulidos** [comment]
@mattwthompson oh maybe it's worth mentioning that this is with `openff-toolkit=0.11.2` which was what `mamba upgrade -c conda-forge openff-toolkit` resulted with in my freshly created environment.

**Comment by ijpulidos** [comment]
@mattwthompson managed to get `openff-toolkit=0.12.1` running on the environment and it's passed that point and stuck for a while doing the `sqm` computations, so I think this is already solved in that version of the toolkit. FYI.

**Comment by mattwthompson** [comment]
Bumping up to 0.12 would be nice for some other features (I think better error handling on loading force fields). 0.13.0 just dropped but shouldn't include changes that are relevant here

**Comment by mikemhenry** [comment]
If we can bump to 0.12, that would be great. I think everything else in the ecosystem support 0.12 so it would be nice to get that working

**Comment by mattwthompson** [comment]
Does anything need < 0.11.0? As I understand it, our infrastructure completely supports everything that was previously parked in the 0.10.x line, although we formally have a couple of months left of offering critical bugfixes for that line

**Comment by mikemhenry** [comment]
I think perses might need 0.11, but we have a pr for 0.12 so I can't think of anything using 0.11 still

**Comment by mattwthompson** [comment]
If nothing **needs** 0.10.7, it'd be easiest to just remove the `Latest openff-toolkit false` cases from the matrix

**Comment by jchodera** [comment]
Closing this since we refreshed the OpenEye license.

**Pull request closed without merging**
